version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 3.4641016
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
customportalapi = true
naturalist = true
techreborn = true
portablehole = true
cccbridge = true
botania = true
megacells = true
spectrum = true
bedspreads = true
deeperdarker = true
create = true
redbits = true
friendsandfoes = true
redstonebits = true
minecraft = true
comforts = true
advanced_reborn = true
archon = true
merequester = true
darkutils = true
yigd = true
ae2 = true
things = true
railways = true
quarrymod = true
createaddition = true
appbot = true
bellsandwhistles = true
milk = true
display_case = true
rocks = true
diagonalwindows = true
itemalchemy = true
moderndynamics = true
computercraft = true
diagonalfences = true
extendedgears = true
bewitchment = true
modern_industrialization = true
ad_astra = true
thinair = true
